# Generated by Django 4.1.1 on 2022-09-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='自己紹介'),
        ),
    ]
